services:
  app:
    build: .
    container_name: laravel_api
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql

    command: >
      sh -c "
      php artisan migrate &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: